apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: demo-policies
  namespace: acm-policies
spec:
  type: GitHub
  pathname: https://github.com/rupadhy3/rhacm-app-policy.git
